"""todo table

Revision ID: 607aac54dc2a
Revises: 
Create Date: 2021-12-29 20:23:18.795130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607aac54dc2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_tasks'), 'todo', ['tasks'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_tasks'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
