"""empty message

Revision ID: 8ea0bef261e8
Revises: 82dafa176f1c
Create Date: 2021-12-30 09:41:00.005921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea0bef261e8'
down_revision = '82dafa176f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'created_date')
    # ### end Alembic commands ###
