"""update todo table

Revision ID: 9d27bb632d1b
Revises: 607aac54dc2a
Create Date: 2021-12-29 21:32:01.314408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d27bb632d1b'
down_revision = '607aac54dc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('title', sa.String(length=20), nullable=False))
    op.add_column('todo', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('todo', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=False))
    op.drop_index('ix_todo_tasks', table_name='todo')
    op.drop_column('todo', 'tasks')
    op.drop_column('todo', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('todo', sa.Column('tasks', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_todo_tasks', 'todo', ['tasks'], unique=False)
    op.drop_column('todo', 'complete')
    op.drop_column('todo', 'date_posted')
    op.drop_column('todo', 'description')
    op.drop_column('todo', 'title')
    # ### end Alembic commands ###
