"""empty message

Revision ID: bedbf6145a97
Revises: 9d27bb632d1b
Create Date: 2021-12-30 00:21:09.083253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedbf6145a97'
down_revision = '9d27bb632d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###
